#!/bin/sh -ue

# cronjob; output $file checked with i3status
file="$HOME/.gmail-unread"

temp="${TMPDIR:-/tmp}/check-gmail.$$"
trap 'rm "$temp"' EXIT
"$(dirname "$0")/gmail-unread" >"$temp"
mv "$temp" "$file"
trap - EXIT
