#!/bin/sh -ue

fatal() {
    printf %s\\n "$(basename "$0"): $2" >&2
    exit "$1"
}

handle_option() {
    case "$1" in
        *)
            fatal 64 "unknown option: $1"
            ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            break ;;
        --*=*)
            x="${1#--}"
            handle_option "${x%%=*}" "${x#*=}"
            shift ;;
        --*)
            handle_option "${1#--}"
            shift ;;
        -?*)
            if [ ${#1} = 2 ]; then
                handle_option "${1#-}"
            else
                v="${1#??}"
                x="${1%"$v"}"
                handle_option "${x#-}" "$v"
            fi
            shift ;;
        *)
            break ;;
    esac
done

if [ $# = 0 ]; then
    fatal 64 'usage: FILE..'
fi

for fn; do
    if [ -L "$fn" ]; then
        fatal 1 "symlink: $fn"
    elif [ ! -e "$fn" -o -s "$fn" ]; then
        true
    else
        rm -- "$fn"
    fi
done
