#!/bin/sh -ue
#.help
# fzt
#
# Run fzf; echo output and set tmux buffer.
#
# Options:
# -cX --cd=X        cd X before fzt; prepend X/ to result
#
# Options for fzf:
# -m  --multi       fzf --multi

fatal() {
    printf %s\\n "$(basename "$0") error: $2" >&2
    exit "$1"
}

base_dir=
fzf_multi=
handle_option() {
    case "$1" in
        c|cd)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            base_dir="$2"
            ;;
        m|multi)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fzf_multi=--multi
            ;;
        no-multi)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fzf_multi=
            ;;
        *)
            fatal 64 "unknown option: $1"
            ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            break;;
        --*=*)
            x="${1#--}"
            handle_option "${x%%=*}" "${x#*=}"
            shift;;
        --*)
            handle_option "${1#--}"
            shift;;
        -?*)
            if [ ${#1} = 2 ]; then
                handle_option "${1#-}"
            else
                v="${1#??}"
                x="${1%"$v"}"
                handle_option "${x#-}" "$v"
            fi
            shift;;
        *)
            break;;
    esac
done


if [ -z "${TMUX:-}" ]; then
    fatal 64 'not inside tmux'
fi
if [ -n "$base_dir" ]; then
    cd -- "$base_dir" || fatal 65 "change directory failure: $base_dir"
fi
results="$(fzf $fzf_multi)" || exit $?
if [ -n "$base_dir" ]; then
    if [ -z "$fzf_multi" ]; then
        case "$base_dir" in
            */) results="$base_dir$results" ;;
            *)  results="$base_dir/$results" ;;
        esac
    else
        fatal 70 TODO
    fi
fi
printf %s\\n "$results"
tmux set-buffer -- "$results"
