#!/bin/sh -Cue
#.help
# % [...]
#
# Use $HOME hg repository which is only available while requested.
#
# * `ln -s .hhg ~/.hg`
# * `hg "$@"`
# * `rm ~/.hg`
#
# To start:
# * `hg init`
# * `mv .hg .hhg`
# * `printf %s\\n 'syntax: glob' '*' > ~/.hgignore`
#
# Note: This is an imperfect solution.

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }

[ -e ~/.hhg ] || fatal 65 'missing ~/.hhg'
ln -s .hhg ~/.hg
rc=0
hg "$@" || rc=$?
rm ~/.hg
exit $rc
