#!/bin/sh -Cue
# into DEST COMMAND..
#
# Rearrange args and execute COMMAND.. DEST.  Useful for tools which append args to generate a command, eg. "find ... -exec into DEST mv".

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }

while [ $# -gt 0 ]; do case "$1" in --) shift; break ;; -) break ;; -*) fatal 64 'unexpected option' ;; *) break ;; esac; done
case $# in
    0) fatal 64 'missing DEST COMMAND.. arguments' ;;
    1) fatal 64 'missing COMMAND.. arguments' ;;
    esac

dest="$1"
shift
exec "$@" "$dest"
