#!/bin/sh -ue
#.help
# % [FILE]
#
# Paste file or stdin to http://ix.io/.  If desired, put username/password into ~/.netrc (not secured through https!).  View your pastes at http://ix.io/user/USER.
#
# Options:
# -iX --id=ID                   replace ID, if you have permission
#     --reads=NUM               paste will be deleted after NUM reads
#
# Examples:
#   ix hello.txt                # paste file (name/ext will be set)
#   echo 'Hello world.' | ix    # read from STDIN (won't set name/ext)
#   ix -n1 self-destruct.txt    # paste will be deleted after one read
#   ix -iID hello.txt           # replace ID, if you have permission
#
# Adapted from http://ix.io/client.

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
is_digits() { for x; do case "$x" in *[!0123456789]*|'') return 1 ;; esac; done; }

max_reads=
id=
handle_option() {
    case "$1" in
        i|id)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "empty value for option $1"
            id="$2"
            ;;
        reads)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            is_digits "$2" || fatal 64 "expected number for option $1"
            max_reads="$2"
            ;;
        *) fatal 64 "unknown option: $1" ;;
        esac
    }
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --=*) fatal 64 'missing option name' ;;
        --*=*)
            x="${1#--}"
            v="${x#*=}"
            x="${x%%=*}"
            case "$x" in
                #*[ `~!@#$%^&*=\\|;'"?]*) fatal 64 'bad option name' ;;
                :)
                    shift
                    x="$v"
                    while [ -n "$x" ]; do
                        v="${x%?}"
                        set -- -"${x#"$v"}" "$@"
                        x="$v"
                        done
                    ;;
                :*) fatal 64 'bad option name' ;;
                *)
                    handle_option "$x" "$v"
                    shift
                    ;;
                esac
            ;;
        --:*) fatal 64 'bad option name' ;;
        --*) handle_option "${1#--}"; shift ;;
        #-[ `~!@#$%^&*=\\|;'"?]*) fatal 64 'bad option name' ;;
        -:*)
            x="${1#??}"
            shift
            while [ -n "$x" ]; do
                v="${x%?}"
                set -- -"${x#"$v"}" "$@"
                x="$v"
                done
            ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
        esac
    done

case $# in
    0) filename='<-' ;;
    1)
        if [ x- = x"$1" ]; then
            filename='<-'
        else
            filename="@$1"
        fi
        ;;
    *) fatal 64 'bad arguments' ;;
esac
if [ -s ~/.netrc ]; then
    curl() { command curl -n "$@"; }
fi
exec curl \
    ${id:+-X PUT} \
    ${max_reads:+-F read:1="$max_reads"} \
    -F f:1="$filename" \
    "http://ix.io/$id"
