#!/bin/sh -Cue
#.help
# % [DEST]
#
# Add symlinks to DEST (default /cmd) for all regular files (or symlinks to regular files) in the six directories {/usr/local,/usr,}/{sbin,bin}.
#
# Options:
#     --dry-run               print files that would be symlinked
#     --path=DIRS             use source DIRS

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
nonfatal() { printf %s\\n "${0##*/}: $*" >&2 || true; }

dryrun=false
path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
handle_option() {
    case "$1" in
        dry-run)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            dryrun=true
            ;;
        path)
            [ -n "${2:-}" ] || fatal 64 "missing value for option $1"
            path="$2"
            ;;
        *) fatal 64 "unknown option $1" ;;
        esac
    }
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --=*) fatal 64 'missing option name' ;;
        --*=*)
            x="${1#--}"
            v="${x#*=}"
            x="${x%%=*}"
            case "$x" in
                :?*|*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
                :)
                    shift
                    x="$v"
                    while [ -n "$x" ]; do
                        v="${x%?}"
                        set -- -"${x#"$v"}" "$@"
                        x="$v"
                        done
                    ;;
                *)
                    handle_option "$x" "$v"
                    shift
                    ;;
                esac
            ;;
        --:) shift ;;
        --:*|--*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
        --*) handle_option "${1#--}"; shift ;;
        -[\ \`\~\!\@\#\$\%\^\&\*\=\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
        -:*)
            x="${1#??}"
            shift
            while [ -n "$x" ]; do
                v="${x%?}"
                set -- -"${x#"$v"}" "$@"
                x="$v"
                done
            ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
        esac
    done
case "$#" in
    0) set -- /cmd ;;
    1) ;;
    *) fatal 64 'unexpected arguments' ;;
    esac
dest="$1"
[ -n "$dest" ] || fatal 65 'empty destination'
dest="$(printf %s "$dest" | sed -r 's,/+$,,')"
[ -n "$dest" ] || fatal 65 'disallowed destination: /'

[ -d "$dest" ] || fatal 65 "destination missing: $dest"
printf %s "$path:" | tr : \\n |
while IFS= read -r src; do
    if [ -z "$src" ]; then
        nonfatal 'skipping empty path entry'
        continue
        fi
    if [ ! -e "$src" ]; then
        nonfatal "skipping missing path entry: $src"
        continue
        fi
    if [ ! -d "$src" ]; then
        nonfatal "skipping non-directory path entry: $src"
        continue
        fi
    case "$src" in
        /*) ;;
        *)
            nonfatal 'skipping relative path entry'
            continue
            ;;
        esac
    for file in "$(readlink -f -- "$src")"/*; do
        [ -f "$file" ] || continue
        b="${file##*/}"
        if [ -e "$dest/$b" ]; then
            if [ ! -L "$dest/$b" ] || [ "$file" -ef "$dest/$b" ]; then
                # ignore non-link files: assumed to intentionally shadow
                # ignore if links to the same final dest
                continue
                fi
            nonfatal "$dest/$b: $(readlink "$dest/$b") shadows $file"
        elif $dryrun; then
            printf %s\\n "$file"
        else
            ln -s -f "$file" "$dest/$b"
            fi
        done
    done
