#!/bin/sh -ue
#.help
# tarsnap-backup NAME PATH..
#
# Backup PATHs into tarsnap archive NAME.YYYY-MM-DD_HH:NN:SS (in UTC).
#
# Options:
#     --dry-run             show create command without executing
#     --quiet               no output on success
#
# Tarsnap Options:
#     --tarsnap=TARSNAP     use TARSNAP instead of "tarsnap" command
#     --keyfile=KEYFILE     tarsnap --keyfile

fatal() {
    printf %s\\n "$(basename "$0") error: $2" >&2
    exit "$1"
}
is_digits() {
    local x; for x; do case "$x" in *[!0-9]*|'') return 1 ;; *) ;; esac done
}
is_integer() {
    local x; for x; do case "$x" in -*) is_digits "${x#-}" || return 1 ;; *[!0-9]*|'') return 1 ;; *) ;; esac done
}

dry_run=false
verbose=true
tarsnap=tarsnap
keyfile=
handle_option() {
    case "$1" in
        # add options here, with common checks:
            #[ $# = 2 ] || fatal 64 "missing value for option $1"
            #[ $# = 1 ] || fatal 64 "unexpected value for option $1"
            #is_digits "$2" || fatal 64 "expected (non-negative) integer for option $1"
            #is_integer "$2" || fatal 64 "expected integer for option $1"
        # less commonly useful:
            #[ -n "$2" ] || fatal 64 "expected non-empty value for option $1"
            # $2 is only empty for "--long-option=" (equals with no following value)

        dry-run)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            dry_run=true
            ;;
        quiet)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            verbose=false
            ;;
        tarsnap)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "expected non-empty value for option $1"
            tarsnap="$2"
            ;;
        keyfile)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "expected non-empty value for option $1"
            keyfile="$2"
            ;;
        *) fatal 64 "unknown option $1" ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
        --*) handle_option "${1#--}"; shift ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
    esac
done


if [ $# = 0 ]; then
    fatal 64 'missing archive NAME argument'
elif [ $# -lt 2 ]; then
    fatal 64 'missing at least one PATH argument'
fi

case "$1" in
    *.*|*/*|*' '*)
        fatal 64 'invalid archive NAME, cannot contain [./ ]'
        ;;
esac
archive_name="$1.$(date -u +%Y-%m-%d_%H:%M:%S)"
shift

if $verbose || $dry_run; then
    if [ -z "$keyfile" ]; then
        printf '%s \\\n' "$tarsnap -c"
    else
        printf '%s \\\n' "$tarsnap -c --keyfile $keyfile"
    fi
    printf '  -f %s \\\n' "$archive_name"
    printf '  %s \\\n' "$@"
    printf '  # end\n'
    if $dry_run; then
        exit 0
    fi
fi

set -- -f "$archive_name" "$@"
if [ -n "$keyfile" ]; then
    set -- --keyfile "$keyfile" "$@"
fi
exec "$tarsnap" -c "$@"
