#!/bin/sh -ue
#.help
# tarsnap-backup NAME PATH..
#
# Backup PATHs into tarsnap archive NAME.YYYY-MM-DD_HH:NN:SS (in UTC).
#
# Options:
#     --dry-run             show create command without executing
#     --quiet               no output on success
#
# Tarsnap Options:
#     --tarsnap=TARSNAP     use TARSNAP instead of "tarsnap" command
#     --keyfile=KEYFILE     tarsnap --keyfile

fatal() {
    printf %s\\n "$(basename "$0") error: $2" >&2
    exit "$1"
}

dry_run=false
verbose=true
tarsnap=tarsnap
keyfile=
handle_option() {
    case "$1" in
        dry-run)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            dry_run=true
            ;;
        quiet)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            verbose=false
            ;;
        tarsnap)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "expected non-empty value for option $1"
            tarsnap="$2"
            ;;
        keyfile)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "expected non-empty value for option $1"
            keyfile="$2"
            ;;
        *) fatal 64 "unknown option $1" ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
        --*) handle_option "${1#--}"; shift ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
    esac
done


if [ $# = 0 ]; then
    fatal 64 'missing archive NAME argument'
elif [ $# -lt 2 ]; then
    fatal 64 'missing at least one PATH argument'
fi

case "$1" in
    *[/' ']*)
        fatal 64 'invalid archive NAME, cannot contain [/ ]'
        ;;
esac
archive_name="$1.$(date -u +%Y-%m-%d_%H:%M:%S)"
shift

if $verbose || $dry_run; then
    printf %s "$tarsnap -c"
    if [ -n "$keyfile" ]; then
        printf ' %s' "--keyfile $keyfile"
    fi
    printf ' -f %s' "$archive_name"
    printf ' %s' "$@"
    printf \\n
    if $dry_run; then
        exit 0
    fi
fi

set -- -f "$archive_name" "$@"
if [ -n "$keyfile" ]; then
    set -- --keyfile "$keyfile" "$@"
fi
exec "$tarsnap" -c "$@"
