#!/bin/sh -ue

fatal() {
    printf '%s: error: %s\n' "$(basename "$0")" "$2" >&2
    exit "$1"
}

buffer=
handle_option() {
    case "$1" in
        b)
            [ $# = 2 ] || fatal 1 'missing -b value'
            buffer="$2";;
        *)
            fatal 1 "unknown option: $1";;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            break;;
        --*=*)
            x="${1#--}"
            handle_option "${x%%=*}" "${x#*=}"
            shift;;
        --*)
            handle_option "${1#--}"
            shift;;
        -?*)
            if [ ${#1} = 2 ]; then
                handle_option "${1#-}"
            else
                v="${1#??}"
                x="${1%"$v"}"
                handle_option "${x#-}" "$v"
            fi
            shift;;
        *)
            break;;
    esac
done

case $# in
    0)
        set -- -;;
    1)
        ;;
    *)
        fatal 1 'unexpected arguments';;
esac
if [ -n "$buffer" ]; then
    set -- -b "$buffer" "$@"
fi
if [ -t 0 -a x"$1" = x- ]; then
    cat | tmux load-buffer "$@"
else
    exec tmux load-buffer "$@"
fi
