#!/bin/sh -Cue
#.help
# %
#
# Create Borderless theme for XFCE / XFWM4.

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
nonfatal() { printf %s\\n "${0##*/}: $*" >&2 || true; }

while [ $# -gt 0 ]; do case "$1" in --) shift; break ;; -) break ;; -*) fatal 64 'unexpected option' ;; *) break ;; esac; done
[ $# = 0 ] || fatal 64 'unexpected arguments'

target=/usr/share/themes/Borderless
if [ -e "$target" ]; then
    fatal 65 "already exists: $target"
    fi
mkdir -p "$target/xfwm4" || fatal $? "are permissions required to create $target?"
touch "$target/themerc" || fatal $? "are permissions required to create $target/themerc?"
nonfatal "created: $target"
